name: Deploy ShareMoment API (App Service)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Optional sanity: fail fast if package.json/scripts are missing
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci --omit=dev

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ShareMoment1'   # <-- EXACT App Service name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A369F7F4214149E98060A107FA57740F }}
          package: '.'               # <-- DEPLOY THE REPO ROOT


